version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: ${DL_PG_NAME:-domain_locker}
      POSTGRES_USER: ${DL_PG_USER:-postgres}
      POSTGRES_PASSWORD: ${DL_PG_PASSWORD:-changeme2420}
    ports:
      - "${DL_PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - domain_locker_network

  app:
    image: domain-locker:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    environment:
      DL_ENV_TYPE: ${DL_ENV_TYPE:-selfHosted}
      SUPABASE_URL: ${SUPABASE_URL:-""}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:-""}
      DL_PG_HOST: postgres
      DL_PG_PORT: 5432
      DL_PG_USER: ${DL_PG_USER:-postgres}
      DL_PG_PASSWORD: ${DL_PG_PASSWORD:-changeme2420}
      DL_PG_NAME: ${DL_PG_NAME:-domain_locker}
    ports:
      - "3000:3000"
    networks:
      - domain_locker_network

volumes:
  postgres_data:

networks:
  domain_locker_network:
    driver: overlay
