name: 🥏 Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Changelog
        id: changelog
        run: |
          echo "## Changelog" > RELEASE.md
          git log --oneline $(git describe --tags --abbrev=0 @^)..@ >> RELEASE.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: RELEASE.md
